version: 2
secret:
  ignored-paths:
    - "android/app/build/**"
    - "**/test/**"
    - "**/tests/**"
    - "**/*.test.*"
    - "**/*.spec.*"
  ignored-matches:
    - name: "Ignore Example Keys"
      match: AKIA5XXXXXXXXXXXXXXXXX
    - name: "Ignore Test Tokens"
      match: "test_token_*"

paths-ignore:
  - "**/*.lock"
  - "**/dist/**"
  - "**/build/**"
  - "**/.git/**"
  - "**/.env.example"
  - "**/node_modules/**"

matches-ignore:
  - name: "Localhost URLs"
    match: "http://localhost:*"
  - name: "Example Credentials"
    match: "example_key_*"
