name: Android Build

on:
  push:
    branches:
      - main
    paths:
      - 'android/**'
      - '.github/workflows/android.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create debug keystore
        working-directory: ./android/app
        run: |
          keytool -genkey -v -keystore debug.keystore \
            -storepass android -alias androiddebugkey \
            -keypass android -keyalg RSA -keysize 2048 \
            -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -d > android/app/google-services.json
          ls -la android/app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Debug APK
        working-directory: ./android
        run: |
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace
          ls -la app/build/outputs/apk/debug/

      - name: Debug Firebase Configuration
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          # Install Firebase CLI
          curl -sL https://firebase.tools | bash
          
          # Save service account key
          echo '${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}' > firebase-service-account.json
          
          # Set environment variables
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json
          
          echo "=== Firebase Project Information ==="
          echo "Project ID: $FIREBASE_PROJECT_ID"
          echo "App ID: $FIREBASE_APP_ID"
          
          echo "=== Listing Firebase Projects ==="
          firebase projects:list
          
          echo "=== Listing Android Apps in Project ==="
          firebase apps:list ANDROID --project $FIREBASE_PROJECT_ID
          
          echo "=== Verifying App Distribution Setup ==="
          firebase appdistribution:apps:list --project $FIREBASE_PROJECT_ID

      - name: Upload to Firebase App Distribution
        if: success()
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          # Verify app exists
          firebase apps:list ANDROID --project $FIREBASE_PROJECT_ID | grep $FIREBASE_APP_ID || {
            echo "Error: App ID $FIREBASE_APP_ID not found in project. Please verify the app is registered in Firebase Console."
            exit 1
          }
          
          # Upload APK
          firebase appdistribution:distribute android/app/build/outputs/apk/debug/app-debug.apk \
            --app $FIREBASE_APP_ID \
            --token "$FIREBASE_TOKEN" \
            --groups "testers" \
            --release-notes "Debug build with latest changes from $(git rev-parse --short HEAD)"

      - name: Clean up secrets
        if: always()
        run: |
          rm -f android/app/google-services.json
          rm -f android/app/debug.keystore
          rm -f firebase-service-account.json
