name: Android Build

on:
  push:
    branches:
      - main
    paths:
      - 'android/**'
      - '.github/workflows/android.yml'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create debug keystore
        working-directory: ./android/app
        run: |
          keytool -genkey -v -keystore debug.keystore \
            -storepass android -alias androiddebugkey \
            -keypass android -keyalg RSA -keysize 2048 \
            -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -d > android/app/google-services.json
          ls -la android/app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Debug APK
        working-directory: ./android
        run: |
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace
          ls -la app/build/outputs/apk/debug/

      - name: Setup Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          echo '${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}' > firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json
          firebase --token '${{ secrets.FIREBASE_TOKEN }}' projects:list

      - name: Upload to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          firebase appdistribution:distribute android/app/build/outputs/apk/debug/app-debug.apk \
            --app $FIREBASE_APP_ID \
            --token "$FIREBASE_TOKEN" \
            --groups "testers" \
            --release-notes "Debug build with latest changes"

      - name: Clean up secrets
        if: always()
        run: |
          rm -f android/app/google-services.json
          rm -f android/app/debug.keystore
          rm -f firebase-service-account.json
