name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: android
      
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: android
      
    - name: Run Tests
      run: ./gradlew test
      working-directory: android
      
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: android/app/build/reports/tests/
        
    - name: Upload Coverage Reports
      uses: codecov/codecov-action@v3
      with:
        directory: android/app/build/reports/coverage/
        fail_ci_if_error: true
