name: Build and Distribute App

on:
  push:
    branches:
      - main
    paths:
      - 'android/**'
      - '.github/workflows/distribute.yml'

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -d > android/app/google-services.json

      - name: Decode Firebase Service Account
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo $FIREBASE_SERVICE_ACCOUNT | base64 -d > firebase-service-account.json

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload Debug APK to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          cd android
          ./gradlew appDistributionUploadDebug \
            -PfirebaseAppId=$FIREBASE_APP_ID \
            -PfirebaseToken=$FIREBASE_TOKEN

      - name: Notify on Success
        if: success()
        run: |
          echo "App successfully distributed! Check your email for the download link."

      - name: Clean up secrets
        if: always()
        run: |
          rm -f android/app/google-services.json
          rm -f firebase-service-account.json
