name: Build and Distribute App

on:
  push:
    branches:
      - main
    paths:
      - 'android/**'
      - '.github/workflows/distribute.yml'

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Firebase CLI
        run: |
          npm install -g firebase-tools
          firebase --version

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -d > android/app/google-services.json
          ls -la android/app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Clean project
        run: |
          cd android
          ./gradlew clean --info

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --info
          ls -la app/build/outputs/apk/debug/

      - name: Upload Debug APK to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          echo "Uploading APK to Firebase App Distribution..."
          echo "App ID: $FIREBASE_APP_ID"
          cd android
          ./gradlew appDistributionUploadDebug \
            -PfirebaseAppId=$FIREBASE_APP_ID \
            -PfirebaseToken=$FIREBASE_TOKEN \
            --info

      - name: Notify on Success
        if: success()
        run: |
          echo "App successfully distributed! Check your email for the download link."

      - name: Clean up secrets
        if: always()
        run: |
          rm -f android/app/google-services.json
