name: Build and Distribute App

on:
  push:
    branches:
      - main
    paths:
      - 'android/**'
      - '.github/workflows/distribute.yml'

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Firebase CLI
        run: |
          npm install -g firebase-tools
          firebase --version

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -d > android/app/google-services.json
          ls -la android/app/google-services.json

      - name: Decode Firebase Service Account
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo $FIREBASE_SERVICE_ACCOUNT | base64 -d > firebase-service-account.json
          ls -la firebase-service-account.json

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Clean project
        run: |
          cd android
          ./gradlew clean --stacktrace

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --info --stacktrace
          ls -la app/build/outputs/apk/debug/

      - name: Upload Debug APK to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          echo "Uploading APK to Firebase App Distribution..."
          echo "App ID: $FIREBASE_APP_ID"
          firebase appdistribution:distribute android/app/build/outputs/apk/debug/app-debug.apk \
            --app $FIREBASE_APP_ID \
            --token "$FIREBASE_TOKEN" \
            --groups "testers" \
            --release-notes "Debug build with latest changes" \
            --debug

      - name: Notify on Success
        if: success()
        run: |
          echo "App successfully distributed! Check your email for the download link."

      - name: Clean up secrets
        if: always()
        run: |
          rm -f android/app/google-services.json
          rm -f firebase-service-account.json
