name: Build and Distribute App

on:
  push:
    branches:
      - main
    paths:
      - 'android/**'
      - '.github/workflows/distribute.yml'

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -d > android/app/google-services.json
          ls -la android/app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleDebug --debug
          ls -la app/build/outputs/apk/debug/

      # Primary distribution method
      - name: Upload Debug APK to Firebase App Distribution (Primary)
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: android/app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: "Debug build with latest changes"
        continue-on-error: true
        id: primary_upload

      # Backup distribution method using Firebase CLI
      - name: Setup Node.js (Backup)
        if: steps.primary_upload.outcome == 'failure'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI (Backup)
        if: steps.primary_upload.outcome == 'failure'
        run: npm install -g firebase-tools

      - name: Upload Debug APK to Firebase App Distribution (Backup)
        if: steps.primary_upload.outcome == 'failure'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          firebase appdistribution:distribute android/app/build/outputs/apk/debug/app-debug.apk \
            --app $FIREBASE_APP_ID \
            --token "$FIREBASE_TOKEN" \
            --groups "testers" \
            --release-notes "Debug build with latest changes"

      - name: Notify on Success
        if: success()
        run: |
          echo "App successfully distributed! Check your email for the download link."

      - name: Clean up secrets
        if: always()
        run: |
          rm -f android/app/google-services.json
